//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QQ112
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID_users { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string FIO { get; set; }
        public Nullable<int> ID_Role { get; set; }
    }
}
